# Generated by Django 6.0 on 2026-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0004_trekimage_image_url_alter_trekimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treklist',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treklist',
            name='pin_priority',
            field=models.PositiveIntegerField(blank=True, help_text='Lower number = higher priority (1 comes first)', null=True),
        ),
    ]
