# Generated by Django 6.0 on 2026-01-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0005_treklist_is_pinned_treklist_pin_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='additional_images',
        ),
    ]
