# Generated by Django 6.0 on 2026-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0006_remove_trek_additional_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='trek_images', to='treks_app.trekimage'),
        ),
    ]
